// GENERATED by scripts/gen-admin-changelog.mjs — do not edit by hand.
import type { AdminCommitEntry } from "./adminChangelog";

export const ADMIN_COMMITS: AdminCommitEntry[] = [
  {
    "hash": "9db267c",
    "date": "2026-10-04",
    "type": "FEAT",
    "scope": "admin",
    "desc": "auto-collect admin-scoped commits into the 변경 기록 tab, add type/month/source filters, make patch-note length limit a constant"
  },
  {
    "hash": "d7105f4",
    "date": "2026-10-02",
    "type": "FEAT",
    "scope": "analytics",
    "desc": "keep Claude's test visits, labelled as 🤖 클로드"
  },
  {
    "hash": "f440881",
    "date": "2026-10-02",
    "type": "FEAT",
    "scope": "admin",
    "desc": "focus every stat on named IPs or one named person"
  },
  {
    "hash": "346276d",
    "date": "2026-10-02",
    "type": "FEAT",
    "scope": "visitors",
    "desc": "open without the page password when signed in as admin"
  },
  {
    "hash": "a73d738",
    "date": "2026-10-02",
    "type": "FIX",
    "scope": "admin",
    "desc": "page crash when a named person visited without playing"
  },
  {
    "hash": "23d70a7",
    "date": "2026-10-02",
    "type": "FEAT",
    "scope": "admin",
    "desc": "phone alerts via ntfy when chosen named IPs visit or play"
  },
  {
    "hash": "67182bd",
    "date": "2026-10-02",
    "type": "FEAT",
    "scope": "admin",
    "desc": "alert when a named IP comes back; exclude named IPs from stats"
  },
  {
    "hash": "840e67e",
    "date": "2026-10-02",
    "type": "FEAT",
    "scope": "admin",
    "desc": "name frequent IPs (IP 관리 tab)"
  },
  {
    "hash": "fd0f640",
    "date": "2026-10-02",
    "type": "FEAT",
    "scope": "admin",
    "desc": "monthly stats tab"
  },
  {
    "hash": "a09468b",
    "date": "2026-10-01",
    "type": "FEAT",
    "scope": "admin",
    "desc": "warn when admin_suite.sql hasn't been applied"
  },
  {
    "hash": "4deba2c",
    "date": "2026-10-01",
    "type": "FEAT",
    "scope": "admin",
    "desc": "trends, hours, drop-off, rooms, sources, exclude-me, bugs, notice, game visibility"
  },
  {
    "hash": "1f01d6a",
    "date": "2026-10-01",
    "type": "FEAT",
    "scope": "admin",
    "desc": "reveal device IPs on click, show the admin's own IP by default"
  },
  {
    "hash": "7205821",
    "date": "2026-10-01",
    "type": "FEAT",
    "scope": "admin",
    "desc": "🛠 관리자 link in the header for site admins; refresh auth after login"
  },
  {
    "hash": "939787d",
    "date": "2026-10-01",
    "type": "FEAT",
    "scope": "analytics",
    "desc": "per-game funnel events, admin dashboard, count real starts only"
  },
  {
    "hash": "cf737ac",
    "date": "2026-10-01",
    "type": "FEAT",
    "scope": "analytics",
    "desc": "/visitors page — who visited and who came back"
  },
  {
    "hash": "c6fed0c",
    "date": "2026-10-01",
    "type": "FIX",
    "scope": "analytics",
    "desc": "keep automated browsers out of the public play count"
  },
  {
    "hash": "151e7b6",
    "date": "2026-10-01",
    "type": "FIX",
    "scope": "analytics",
    "desc": "count plays from production only; standalone play-count SQL"
  },
  {
    "hash": "2e6c972",
    "date": "2026-09-03",
    "type": "FEAT",
    "scope": "analytics",
    "desc": "implement file-based daily/monthly site visits and game play statistics without external services"
  },
  {
    "hash": "6effc6b",
    "date": "2026-08-27",
    "type": "FIX",
    "scope": "admin",
    "desc": "default the entitlements kill switch to OFF"
  },
  {
    "hash": "0acb64f",
    "date": "2026-08-27",
    "type": "FEAT",
    "scope": "admin",
    "desc": "add super-admin-only kill switch for entitlement caps"
  },
  {
    "hash": "123e054",
    "date": "2026-08-26",
    "type": "FEAT",
    "scope": "analytics",
    "desc": "implement visitor tracking, game play metrics, and admin stats dashboard"
  }
];
